Repository bet-smart-parking/smart-parking-frontend, pull requests merged in 2020-03, with the labels that each got.

#1 feat(home): Finish first page called home
  src/app/App.vue
  src/app/pages/AboutPage.vue
  src/app/pages/BookingConfirmationPage.vue
  src/app/pages/BookingDetailPage.vue
  src/app/pages/BookingFormPage.vue
  src/app/pages/BookingPaymentPage.vue
  src/app/pages/HomePage.vue
  src/app/pages/ObjectDetailPage.vue
  src/app/router/routes.ts
  src/assets/payment-methods.svg
  src/assets/picasso-1.png
  src/i18n/de.ts
  src/main.ts
  src/styles/helpers.scss
  src/styles/styles.scss
  src/styles/utilities/_all.scss
  src/styles/utilities/mixins.scss
  src/styles/utilities/variables.scss
Labels: enhancement

#9 feat(informations): Add contact, about and terms pages
  package.json
  src/app/components/Address.vue
  src/app/components/AppBar.vue
  src/app/components/Carusel.vue
  src/app/components/Categories.vue
  src/app/components/Navigation.vue
  src/app/components/OpeningHours.vue
  src/app/components/Prices.vue
  src/app/components/StateOfSlots.vue
  src/app/data/parking-object.ts
  src/app/data/parking-objects.data.ts
  src/app/models/api-information.model.ts
  src/app/pages/AboutPage.vue
  src/app/pages/ContactPage.vue
  src/app/pages/HomePage.vue
  src/app/pages/ObjectDetailPage.vue
  src/app/pages/TermsPage.vue
  src/app/reactive/api/information.api.ts
  src/app/reactive/api/parking-objects.api.ts
  src/app/router/routes.ts
  src/assets/picasso-1.png
  src/assets/picasso/categories.png
  src/assets/picasso/categories.svg
  src/assets/picasso/image-01.jpeg
  src/assets/picasso/image-02.jpeg
  src/assets/picasso/image-03.jpeg
  src/assets/picasso/map.png
  src/assets/picasso/map.svg
  src/assets/picasso/thumbnail.jpeg
  src/i18n/de.ts
  src/styles/helpers.scss
  src/styles/utilities/mixins.scss
  yarn.lock
Labels: enhancement

#10 feat(booking): Add booking form page
  package.json
  src/app/pages/BookingFormPage.vue
  src/app/pages/BookingVerificationPage.vue
  src/app/pages/ObjectDetailPage.vue
  src/app/reactive/booking-form.state.ts
  src/app/router/routes.ts
  src/i18n/de.ts
  src/types/vue.d.ts
  yarn.lock
Labels: enhancement

#11 feat(booking): Add verification process
  .eslintrc.js
  package.json
  src/app/App.vue
  src/app/components/Address.vue
  src/app/components/AppBar.vue
  src/app/components/BookingForm.vue
  src/app/components/BookingVerification.vue
  src/app/components/Carusel.vue
  src/app/components/Categories.vue
  src/app/components/Navigation.vue
  src/app/components/OpeningHours.vue
  src/app/components/Prices.vue
  src/app/components/StateOfSlots.vue
  src/app/data/parking-object.ts
  src/app/data/parking-objects.data.ts
  src/app/pages/AboutPage.vue
  src/app/pages/BookingConfirmationPage.vue
  src/app/pages/BookingDetailPage.vue
  src/app/pages/BookingFormPage.vue
  src/app/pages/BookingPaymentPage.vue
  src/app/pages/BookingVerificationPage.vue
  src/app/pages/ContactPage.vue
  src/app/pages/HomePage.vue
  src/app/pages/ObjectDetailPage.vue
  src/app/pages/TermsPage.vue
  src/app/reactive/api/information.api.ts
  src/app/reactive/api/parking-objects.api.ts
  src/app/reactive/app-bar.state.ts
  src/app/reactive/booking-form.state.ts
  src/app/router/index.ts
  src/app/router/routes.ts
  src/config/api.config.ts
  src/config/app.config.ts
  src/i18n/de.ts
  src/i18n/en.ts
  src/main.ts
  src/plugins/axios.plugin.ts
  src/plugins/i18n.plugin.ts
  src/plugins/vue-composition-api.plugin.ts
  src/plugins/vue-router.plugin.ts
  src/plugins/vuetify.plugin.ts
  src/registerServiceWorker.ts
  src/types/json.d.ts
  src/types/shims-tsx.d.ts
  src/types/shims-vue.d.ts
  src/types/vue.d.ts
  src/types/vue.types.d.ts
Labels: enhancement

#13 feat(booking): Add booking detail page
  src/app/components/BookingVerification.vue
  src/app/components/Navigation.vue
  src/app/data/parking-objects.data.ts
  src/app/pages/BookingDetailPage.vue
  src/app/pages/ObjectDetailPage.vue
  src/app/utils/date.ts
  src/assets/picasso/image-04.jpg
  src/assets/picasso/image-05.jpg
  src/assets/picasso/image-06.jpg
  src/assets/picasso/image-07.jpg
  src/assets/picasso/image-08.jpg
  src/i18n/de.ts
  src/styles/box.scss
  src/styles/helpers.scss
  src/styles/styles.scss
Labels: enhancement

#19 feat(booking): Add payment page
  src/app/pages/BookingDetailPage.vue
  src/app/pages/BookingFormPage.vue
  src/app/pages/BookingPaymentPage.vue
  src/app/reactive/booking.state.ts
  src/app/utils/date.ts
  src/i18n/de.ts
Labels: enhancement

#20 fix(npm): update deps
  package.json
  src/app/components/BookingForm.vue
  src/app/components/BookingVerification.vue
  src/app/components/Carusel.vue
  src/app/pages/AboutPage.vue
  src/app/pages/BookingConfirmationPage.vue
  src/app/pages/BookingDetailPage.vue
  src/app/pages/BookingPaymentPage.vue
  src/app/pages/ContactPage.vue
  src/app/pages/HomePage.vue
  src/app/pages/ObjectDetailPage.vue
  src/app/pages/TermsPage.vue
  src/styles/styles.scss
  src/styles/utilities/variables.scss
  yarn.lock
Labels: enhancement

#21 fix(npm): add npm resolution
  package.json
Labels: enhancement

#30 fix(): fixed some typos
  src/app/data/parking-objects.data.ts
Labels: bug

#29 fix(): fixed some typos
  src/app/pages/TermsPage.vue
Labels: bug, frontend

#28 fix(): fixed some typos
  src/i18n/de.ts
Labels: bug, frontend

#32 Feat/#16 use endpoints
  src/app/api/booking.api.ts
  src/app/api/index.ts
  src/app/api/info.api.ts
  src/app/components/AppBar.vue
  src/app/components/BookingDetailInfoBox.vue
  src/app/components/BookingDetailSkeleton.vue
  src/app/components/BookingForm.vue
  src/app/components/BookingVerification.vue
  src/app/components/Navigation.vue
  src/app/components/ParkPrice.vue
  src/app/components/ParkTime.vue
  src/app/data/parking-object.ts
  src/app/data/parking-objects.data.ts
  src/app/models/booking-state.ts
  src/app/models/booking.model.ts
  src/app/pages/BookingDetailPage.vue
  src/app/pages/BookingFormPage.vue
  src/app/pages/BookingPaymentPage.vue
  src/app/pages/HomePage.vue
  src/app/pages/ObjectDetailPage.vue
  src/app/reactive/api-information.ts
  src/app/reactive/api/information.api.ts
  src/app/reactive/booking-form.state.ts
  src/app/reactive/booking.state.ts
  src/app/reactive/parking-objects.state.ts
  src/app/utils/date.util.ts
  src/app/utils/price-calculator.util.ts
  src/i18n/de.ts
Labels: enhancement, frontend

#33 Feat/#8 confirmation
  src/app/pages/BookingConfirmationPage.vue
  src/app/pages/BookingDetailPage.vue
  src/app/pages/BookingPaymentPage.vue
  src/assets/car.svg
  src/i18n/de.ts
Labels: enhancement, frontend

#34 Feat/#25 404 page
  src/app/pages/BookingDetailPage.vue
  src/app/pages/BookingPaymentPage.vue
  src/app/pages/NotFoundPage.vue
  src/app/reactive/booking.state.ts
  src/app/router/routes.ts
  src/assets/barrier.svg
  src/i18n/de.ts
Labels: enhancement, frontend
